name: haskell

on:
  push:
    branches:
      - main
    paths:
      - "*.hs"
      - ".github/workflows/haskell.yaml"

  pull_request:
    branches:
      - main
    paths:
      - "*.hs"
      - ".github/workflows/haskell.yaml"


jobs:
  hlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: 'Set up HLint'
      uses: haskell-actions/hlint-setup@v2

    - name: 'Run HLint'
      uses: haskell-actions/hlint-run@v2
      with:
        path: "."
        fail-on: warning
        
  lab2_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: 'Setup Haskell with Stack'
    - uses: actions/setup-haskell@v1.1
      with:
        ghc-version: 'latest' 
        enable-stack: true
        stack-version: 'latest'

    - name: 'Run lab2 tests'
      working-directory: ./lab-hashmap
      run: stack test
  
